trigger:
  branches:
    include:
    - master
variables:
- name: buildConfiguration
  value: 'Release'
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '5.0.x'
        
    - task: CmdLine@2
      displayName: 'dotnet build $(buildConfiguration)'
      inputs:
        script: dotnet build --configuration $(buildConfiguration)
        workingDirectory: 'JoshsJelliesAndJams/'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: true
      
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure subscription 1(916e3336-1de8-428b-81d9-ef20a2cbe4f9)'
        appType: 'webApp'
        WebAppName: 'JoshsJelliesAndJams'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
